version: '3.8'
services:
  frontend:
    image: ${WEIRDFOODSTUDIO_FRONTEND_IMAGE}
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ${WEIRDFOODSTUDIO_SRV_BASE}/nginx/sites-available:/etc/nginx/sites-enabled
      - ${WEIRDFOODSTUDIO_SRV_BASE}/letsencrypt:/etc/letsencrypt
  letsencrypt:
    image: linuxserver/letsencrypt:amd64-1.6.0-ls133
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - URL=weirdfoodstudio.ca
      - SUBDOMAINS=www,
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ${WEIRDFOODSTUDIO_SRV_BASE}/letsencrypt:/config
  ddclient:
    image: linuxserver/ddclient:amd64-v3.9.1-ls39
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ${WEIRDFOODSTUDIO_SRV_BASE}/ddclient:/config
