version: '3.8'
services:
  frontend:
    image: ${WEIRDFOODSTUDIO_FRONTEND_IMAGE}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weirdfoodstudio.rule=Host(`weirdfoodstudio.ca`,`www.weirdfoodstudio.ca`)"
      - "traefik.http.routers.weirdfoodstudio.entrypoints=https"
      - "traefik.http.routers.weirdfoodstudio.tls.certresolver=cloudflaredns"
      - "traefik.http.services.weirdfoodstudio.loadbalancer.server.port=80"
    volumes:
      - ${WEIRDFOODSTUDIO_SRV_BASE}/nginx/sites-available:/etc/nginx/sites-enabled
networks:
  proxy:
    external: true
